import { Layout } from "@/components/Layout";
import "@/styles/globals.css";
import type { AppProps } from "next/app";
import Head from "next/head";
import { Lato } from "next/font/google";
import { QueryClient, QueryClientProvider } from "react-query";
const queryClient = new QueryClient();

const lato = Lato({
  subsets: ["latin"],
  weight: ["100", "300", "700", "400", "900"],
});

export default function App({ Component, pageProps }: AppProps) {
  return (
    <QueryClientProvider client={queryClient}>
      <Layout className={lato.className}>
        <>
          <Head>
            <title>KPI Dashboard</title>
            <meta name="description" content="Generated by create next app" />
            <meta
              name="viewport"
              content="width=device-width, initial-scale=1"
            />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <Component {...pageProps} />
        </>
      </Layout>
    </QueryClientProvider>
  );
}
